#!/usr/bin/env python3
"""Generate app/src/types/database.ts from the live database.

    cd sync && uv run python ../supabase/gen_types.py

The Supabase CLI can do this too (`supabase gen types`), but its --db-url path needs Docker
and its --project-id path needs an access token. This reads information_schema over the same
SUPABASE_DB_URL the sync job uses and emits the `Database` shape supabase-js expects:
tables with Row/Insert/Update/Relationships, views with Row, and callable functions.
"""

from __future__ import annotations

import sys
from pathlib import Path

import psycopg

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "sync"))
from splitset_sync.config import env  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "app" / "src" / "types" / "database.ts"

SCALAR = {
    "uuid": "string", "text": "string", "character varying": "string", "character": "string", "citext": "string",
    "date": "string", "timestamp with time zone": "string", "timestamp without time zone": "string",
    "time without time zone": "string", "interval": "string", "bytea": "string",
    "integer": "number", "smallint": "number", "bigint": "number", "real": "number",
    "double precision": "number", "numeric": "number",
    "boolean": "boolean", "jsonb": "Json", "json": "Json",
}
ARRAY_ELEMENT = {
    "_int2": "number", "_int4": "number", "_int8": "number", "_float4": "number", "_float8": "number",
    "_numeric": "number", "_text": "string", "_uuid": "string", "_bool": "boolean", "_date": "string",
    "_timestamptz": "string", "_jsonb": "Json",
}
FUNC_ARG = {"text": "string", "date": "string", "uuid": "string", "integer": "number", "boolean": "boolean",
            "jsonb": "Json", "timestamp with time zone": "string"}


def ts_type(data_type: str, udt_name: str) -> str:
    if data_type == "ARRAY":
        return f"{ARRAY_ELEMENT.get(udt_name, 'unknown')}[]"
    if data_type == "USER-DEFINED":
        return "unknown"
    return SCALAR.get(data_type, "unknown")


def q(conn, sql: str, params=None):
    return conn.execute(sql, params).fetchall()


def main() -> None:
    url = env("SUPABASE_DB_URL")
    if not url:
        raise SystemExit("SUPABASE_DB_URL is not set (see .env.example)")
    with psycopg.connect(url, connect_timeout=20) as conn:
        rels = q(conn, """
            select table_name, table_type from information_schema.tables
             where table_schema = 'public' and table_type in ('BASE TABLE', 'VIEW') order by table_name""")
        cols = q(conn, """
            select table_name, column_name, data_type, udt_name, is_nullable = 'YES' as nullable,
                   column_default is not null as has_default, is_identity = 'YES' as is_identity,
                   identity_generation = 'ALWAYS' as identity_always, is_generated = 'ALWAYS' as generated
              from information_schema.columns
             where table_schema = 'public' order by table_name, ordinal_position""")
        fks = q(conn, """
            select c.conname, c.conrelid::regclass::text as tbl,
                   (select array_agg(a.attname order by k.ord) from unnest(c.conkey) with ordinality k(attnum, ord)
                      join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum) as cols,
                   c.confrelid::regclass::text as ref_tbl,
                   (select array_agg(a.attname order by k.ord) from unnest(c.confkey) with ordinality k(attnum, ord)
                      join pg_attribute a on a.attrelid = c.confrelid and a.attnum = k.attnum) as ref_cols,
                   exists (select 1 from pg_constraint u where u.conrelid = c.conrelid and u.contype in ('p', 'u')
                             and u.conkey = c.conkey) as one_to_one
              from pg_constraint c join pg_namespace n on n.oid = c.connamespace
             where c.contype = 'f' and n.nspname = 'public'
               and c.confrelid::regclass::text not like 'auth.%%' and c.confrelid::regclass::text not like 'vault.%%'
             order by 1""")
        funcs = q(conn, """
            select p.proname, pg_get_function_result(p.oid) as result, p.pronargs, p.pronargdefaults,
                   coalesce(p.proargnames, '{}') as argnames,
                   array(select format_type(t, null) from unnest(p.proargtypes) t) as argtypes
              from pg_proc p join pg_namespace n on n.oid = p.pronamespace
             where n.nspname = 'public' and pg_get_function_result(p.oid) not in ('trigger')
             order by 1""")

    by_table: dict[str, list] = {}
    for c in cols:
        by_table.setdefault(c[0], []).append(c)
    fks_by_table: dict[str, list] = {}
    for f in fks:
        fks_by_table.setdefault(f[1], []).append(f)

    out: list[str] = []
    w = out.append
    w("// Generated by supabase/gen_types.py from the live schema. Do not edit by hand.")
    w("")
    w("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]")
    w("")
    w("export type Database = {")
    w("  public: {")
    w("    Tables: {")
    for name, kind in rels:
        if kind != "BASE TABLE":
            continue
        w(f"      {name}: {{")
        w("        Row: {")
        for _, col, dt, udt, nullable, *_ in by_table.get(name, []):
            w(f"          {col}: {ts_type(dt, udt)}{' | null' if nullable else ''}")
        w("        }")
        w("        Insert: {")
        for _, col, dt, udt, nullable, has_default, is_identity, identity_always, generated in by_table.get(name, []):
            if identity_always or generated:
                w(f"          {col}?: never")
            else:
                optional = nullable or has_default or is_identity
                w(f"          {col}{'?' if optional else ''}: {ts_type(dt, udt)}{' | null' if nullable else ''}")
        w("        }")
        w("        Update: {")
        for _, col, dt, udt, nullable, has_default, is_identity, identity_always, generated in by_table.get(name, []):
            if identity_always or generated:
                w(f"          {col}?: never")
            else:
                w(f"          {col}?: {ts_type(dt, udt)}{' | null' if nullable else ''}")
        w("        }")
        w("        Relationships: [")
        for conname, _, fcols, ref_tbl, ref_cols, one_to_one in fks_by_table.get(name, []):
            w("          {")
            w(f'            foreignKeyName: "{conname}"')
            w(f"            columns: [{', '.join(f'\"{c}\"' for c in fcols)}]")
            w(f"            isOneToOne: {'true' if one_to_one else 'false'}")
            w(f'            referencedRelation: "{ref_tbl}"')
            w(f"            referencedColumns: [{', '.join(f'\"{c}\"' for c in ref_cols)}]")
            w("          },")
        w("        ]")
        w("      }")
    w("    }")
    w("    Views: {")
    for name, kind in rels:
        if kind != "VIEW":
            continue
        w(f"      {name}: {{")
        w("        Row: {")
        for _, col, dt, udt, *_ in by_table.get(name, []):
            w(f"          {col}: {ts_type(dt, udt)} | null")
        w("        }")
        w("        Relationships: []")
        w("      }")
    w("    }")
    w("    Functions: {")
    for proname, result, nargs, ndefaults, argnames, argtypes in funcs:
        w(f"      {proname}: {{")
        if nargs:
            w("        Args: {")
            first_default = nargs - ndefaults
            for i, (an, at) in enumerate(zip(argnames, argtypes)):
                w(f"          {an}{'?' if i >= first_default else ''}: {FUNC_ARG.get(at, 'unknown')}")
            w("        }")
        else:
            w("        Args: Record<PropertyKey, never>")
        ret = "undefined" if result == "void" else FUNC_ARG.get(result, "unknown")
        w(f"        Returns: {ret}")
        w("      }")
    w("    }")
    w("    Enums: Record<string, never>")
    w("    CompositeTypes: Record<string, never>")
    w("  }")
    w("}")
    w("")
    w("type PublicSchema = Database[\"public\"]")
    w("")
    w("export type Tables<T extends keyof PublicSchema[\"Tables\"]> = PublicSchema[\"Tables\"][T][\"Row\"]")
    w("export type TablesInsert<T extends keyof PublicSchema[\"Tables\"]> = PublicSchema[\"Tables\"][T][\"Insert\"]")
    w("export type TablesUpdate<T extends keyof PublicSchema[\"Tables\"]> = PublicSchema[\"Tables\"][T][\"Update\"]")
    w("export type Views<T extends keyof PublicSchema[\"Views\"]> = PublicSchema[\"Views\"][T][\"Row\"]")
    w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8")
    n_tables = sum(1 for _, k in rels if k == "BASE TABLE")
    n_views = sum(1 for _, k in rels if k == "VIEW")
    print(f"wrote {OUT.relative_to(OUT.parents[3])}: {n_tables} tables, {n_views} views, {len(funcs)} functions")


if __name__ == "__main__":
    main()
