// Generated by supabase/gen_types.py from the live schema. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      activities: {
        Row: {
          id: string
          user_id: string
          start_time: string
          start_time_local: string
          timezone: string | null
          type: string
          name: string | null
          distance_m: number | null
          moving_time_s: number | null
          elapsed_time_s: number | null
          avg_hr: number | null
          max_hr: number | null
          cadence: number | null
          stride_m: number | null
          gct_ms: number | null
          gct_pct: number | null
          vert_osc_cm: number | null
          vert_ratio: number | null
          avg_power_w: number | null
          vo2max: number | null
          elev_gain_m: number | null
          elev_loss_m: number | null
          load: number | null
          intensity: number | null
          trimp: number | null
          gap_ms: number | null
          avg_temp_c: number | null
          calories: number | null
          resting_hr: number | null
          weight_kg: number | null
          lthr: number | null
          athlete_max_hr: number | null
          device: string | null
          gear_id: string | null
          hr_zone_times: number[] | null
          hr_zones: number[] | null
          pace_zone_times: number[] | null
          raw: Json
          synced_at: string
          updated_at: string
        }
        Insert: {
          id: string
          user_id: string
          start_time: string
          start_time_local: string
          timezone?: string | null
          type: string
          name?: string | null
          distance_m?: number | null
          moving_time_s?: number | null
          elapsed_time_s?: number | null
          avg_hr?: number | null
          max_hr?: number | null
          cadence?: number | null
          stride_m?: number | null
          gct_ms?: number | null
          gct_pct?: number | null
          vert_osc_cm?: number | null
          vert_ratio?: number | null
          avg_power_w?: number | null
          vo2max?: number | null
          elev_gain_m?: number | null
          elev_loss_m?: number | null
          load?: number | null
          intensity?: number | null
          trimp?: number | null
          gap_ms?: number | null
          avg_temp_c?: number | null
          calories?: number | null
          resting_hr?: number | null
          weight_kg?: number | null
          lthr?: number | null
          athlete_max_hr?: number | null
          device?: string | null
          gear_id?: string | null
          hr_zone_times?: number[] | null
          hr_zones?: number[] | null
          pace_zone_times?: number[] | null
          raw: Json
          synced_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          start_time?: string
          start_time_local?: string
          timezone?: string | null
          type?: string
          name?: string | null
          distance_m?: number | null
          moving_time_s?: number | null
          elapsed_time_s?: number | null
          avg_hr?: number | null
          max_hr?: number | null
          cadence?: number | null
          stride_m?: number | null
          gct_ms?: number | null
          gct_pct?: number | null
          vert_osc_cm?: number | null
          vert_ratio?: number | null
          avg_power_w?: number | null
          vo2max?: number | null
          elev_gain_m?: number | null
          elev_loss_m?: number | null
          load?: number | null
          intensity?: number | null
          trimp?: number | null
          gap_ms?: number | null
          avg_temp_c?: number | null
          calories?: number | null
          resting_hr?: number | null
          weight_kg?: number | null
          lthr?: number | null
          athlete_max_hr?: number | null
          device?: string | null
          gear_id?: string | null
          hr_zone_times?: number[] | null
          hr_zones?: number[] | null
          pace_zone_times?: number[] | null
          raw?: Json
          synced_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "activities_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      activity_details: {
        Row: {
          activity_id: string
          user_id: string
          has_streams: boolean
          splits: Json | null
          best_efforts: Json | null
          polyline: string | null
          bbox: number[] | null
          samples: Json | null
          fetched_at: string
        }
        Insert: {
          activity_id: string
          user_id: string
          has_streams: boolean
          splits?: Json | null
          best_efforts?: Json | null
          polyline?: string | null
          bbox?: number[] | null
          samples?: Json | null
          fetched_at?: string
        }
        Update: {
          activity_id?: string
          user_id?: string
          has_streams?: boolean
          splits?: Json | null
          best_efforts?: Json | null
          polyline?: string | null
          bbox?: number[] | null
          samples?: Json | null
          fetched_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_details_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: true
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_details_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      exercises: {
        Row: {
          id: string
          owner_id: string | null
          name: string
          muscle_group: string | null
          equipment: string | null
          measure: string
          is_bodyweight: boolean
          is_unilateral: boolean
          instructions: string | null
          archived: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id?: string | null
          name: string
          muscle_group?: string | null
          equipment?: string | null
          measure?: string
          is_bodyweight?: boolean
          is_unilateral?: boolean
          instructions?: string | null
          archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string | null
          name?: string
          muscle_group?: string | null
          equipment?: string | null
          measure?: string
          is_bodyweight?: boolean
          is_unilateral?: boolean
          instructions?: string | null
          archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "exercises_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      intervals_connections: {
        Row: {
          user_id: string
          athlete_id: string
          api_key_secret_id: string | null
          status: string
          oldest_date: string
          last_synced_at: string | null
          last_success_at: string | null
          last_error: string | null
          consecutive_auth_failures: number
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          athlete_id: string
          api_key_secret_id?: string | null
          status?: string
          oldest_date?: string
          last_synced_at?: string | null
          last_success_at?: string | null
          last_error?: string | null
          consecutive_auth_failures?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          athlete_id?: string
          api_key_secret_id?: string | null
          status?: string
          oldest_date?: string
          last_synced_at?: string | null
          last_success_at?: string | null
          last_error?: string | null
          consecutive_auth_failures?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "intervals_connections_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_sessions: {
        Row: {
          id: string
          user_id: string
          date: string
          position: number
          type: string
          subtype: string | null
          title: string
          target_distance_m: number | null
          target_seconds: number | null
          routine_id: string | null
          notes: string | null
          status: string
          activity_id: string | null
          workout_id: string | null
          linked_by: string | null
          steps: Json | null
          external_event_id: string | null
          external_hash: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          position?: number
          type: string
          subtype?: string | null
          title: string
          target_distance_m?: number | null
          target_seconds?: number | null
          routine_id?: string | null
          notes?: string | null
          status?: string
          activity_id?: string | null
          workout_id?: string | null
          linked_by?: string | null
          steps?: Json | null
          external_event_id?: string | null
          external_hash?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          position?: number
          type?: string
          subtype?: string | null
          title?: string
          target_distance_m?: number | null
          target_seconds?: number | null
          routine_id?: string | null
          notes?: string | null
          status?: string
          activity_id?: string | null
          workout_id?: string | null
          linked_by?: string | null
          steps?: Json | null
          external_event_id?: string | null
          external_hash?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_sessions_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plan_sessions_routine_id_fkey"
            columns: ["routine_id"]
            isOneToOne: false
            referencedRelation: "routines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plan_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plan_sessions_workout_id_fkey"
            columns: ["workout_id"]
            isOneToOne: false
            referencedRelation: "workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          display_name: string
          timezone: string
          units: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name: string
          timezone?: string
          units?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          timezone?: string
          units?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
        ]
      }
      routine_exercises: {
        Row: {
          id: string
          routine_id: string
          user_id: string
          exercise_id: string
          position: number
          superset_group: number | null
          rest_seconds: number | null
          notes: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          routine_id: string
          user_id: string
          exercise_id: string
          position?: number
          superset_group?: number | null
          rest_seconds?: number | null
          notes?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          routine_id?: string
          user_id?: string
          exercise_id?: string
          position?: number
          superset_group?: number | null
          rest_seconds?: number | null
          notes?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "routine_exercises_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "routine_exercises_routine_id_fkey"
            columns: ["routine_id"]
            isOneToOne: false
            referencedRelation: "routines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "routine_exercises_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      routine_sets: {
        Row: {
          id: string
          routine_exercise_id: string
          user_id: string
          position: number
          set_type: string
          target_reps: number | null
          target_reps_max: number | null
          target_weight_kg: number | null
          target_rpe: number | null
          target_seconds: number | null
          updated_at: string
        }
        Insert: {
          id?: string
          routine_exercise_id: string
          user_id: string
          position?: number
          set_type?: string
          target_reps?: number | null
          target_reps_max?: number | null
          target_weight_kg?: number | null
          target_rpe?: number | null
          target_seconds?: number | null
          updated_at?: string
        }
        Update: {
          id?: string
          routine_exercise_id?: string
          user_id?: string
          position?: number
          set_type?: string
          target_reps?: number | null
          target_reps_max?: number | null
          target_weight_kg?: number | null
          target_rpe?: number | null
          target_seconds?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "routine_sets_routine_exercise_id_fkey"
            columns: ["routine_exercise_id"]
            isOneToOne: false
            referencedRelation: "routine_exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "routine_sets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      routines: {
        Row: {
          id: string
          user_id: string
          name: string
          notes: string | null
          position: number
          archived: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          notes?: string | null
          position?: number
          archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          notes?: string | null
          position?: number
          archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "routines_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      sync_runs: {
        Row: {
          id: number
          user_id: string | null
          started_at: string
          finished_at: string | null
          status: string
          triggered_by: string | null
          github_run_id: string | null
          window_oldest: string | null
          window_newest: string | null
          activities_fetched: number
          activities_upserted: number
          streams_fetched: number
          streams_pending: number
          wellness_days: number
          plan_links: number
          error: string | null
        }
        Insert: {
          id?: never
          user_id?: string | null
          started_at?: string
          finished_at?: string | null
          status?: string
          triggered_by?: string | null
          github_run_id?: string | null
          window_oldest?: string | null
          window_newest?: string | null
          activities_fetched?: number
          activities_upserted?: number
          streams_fetched?: number
          streams_pending?: number
          wellness_days?: number
          plan_links?: number
          error?: string | null
        }
        Update: {
          id?: never
          user_id?: string | null
          started_at?: string
          finished_at?: string | null
          status?: string
          triggered_by?: string | null
          github_run_id?: string | null
          window_oldest?: string | null
          window_newest?: string | null
          activities_fetched?: number
          activities_upserted?: number
          streams_fetched?: number
          streams_pending?: number
          wellness_days?: number
          plan_links?: number
          error?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sync_runs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      wellness: {
        Row: {
          user_id: string
          date: string
          resting_hr: number | null
          hrv: number | null
          hrv_sdnn: number | null
          hrv_baseline_low: number | null
          hrv_baseline_high: number | null
          weight_kg: number | null
          body_fat_pct: number | null
          sleep_s: number | null
          sleep_score: number | null
          sleep_quality: number | null
          vo2max: number | null
          ctl: number | null
          atl: number | null
          ramp_rate: number | null
          steps: number | null
          stress: number | null
          respiration: number | null
          spo2: number | null
          readiness: number | null
          source: string
          raw: Json | null
          updated_at: string
        }
        Insert: {
          user_id: string
          date: string
          resting_hr?: number | null
          hrv?: number | null
          hrv_sdnn?: number | null
          hrv_baseline_low?: number | null
          hrv_baseline_high?: number | null
          weight_kg?: number | null
          body_fat_pct?: number | null
          sleep_s?: number | null
          sleep_score?: number | null
          sleep_quality?: number | null
          vo2max?: number | null
          ctl?: number | null
          atl?: number | null
          ramp_rate?: number | null
          steps?: number | null
          stress?: number | null
          respiration?: number | null
          spo2?: number | null
          readiness?: number | null
          source?: string
          raw?: Json | null
          updated_at?: string
        }
        Update: {
          user_id?: string
          date?: string
          resting_hr?: number | null
          hrv?: number | null
          hrv_sdnn?: number | null
          hrv_baseline_low?: number | null
          hrv_baseline_high?: number | null
          weight_kg?: number | null
          body_fat_pct?: number | null
          sleep_s?: number | null
          sleep_score?: number | null
          sleep_quality?: number | null
          vo2max?: number | null
          ctl?: number | null
          atl?: number | null
          ramp_rate?: number | null
          steps?: number | null
          stress?: number | null
          respiration?: number | null
          spo2?: number | null
          readiness?: number | null
          source?: string
          raw?: Json | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "wellness_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      workout_exercises: {
        Row: {
          id: string
          workout_id: string
          user_id: string
          exercise_id: string
          position: number
          superset_group: number | null
          rest_seconds: number | null
          notes: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          workout_id: string
          user_id: string
          exercise_id: string
          position?: number
          superset_group?: number | null
          rest_seconds?: number | null
          notes?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          workout_id?: string
          user_id?: string
          exercise_id?: string
          position?: number
          superset_group?: number | null
          rest_seconds?: number | null
          notes?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_exercises_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_exercises_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_exercises_workout_id_fkey"
            columns: ["workout_id"]
            isOneToOne: false
            referencedRelation: "workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      workout_sets: {
        Row: {
          id: string
          workout_exercise_id: string
          workout_id: string
          exercise_id: string
          user_id: string
          position: number
          set_type: string
          weight_kg: number | null
          reps: number | null
          rpe: number | null
          seconds: number | null
          distance_m: number | null
          completed: boolean
          completed_at: string | null
          notes: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          workout_exercise_id: string
          workout_id: string
          exercise_id: string
          user_id: string
          position?: number
          set_type?: string
          weight_kg?: number | null
          reps?: number | null
          rpe?: number | null
          seconds?: number | null
          distance_m?: number | null
          completed?: boolean
          completed_at?: string | null
          notes?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          workout_exercise_id?: string
          workout_id?: string
          exercise_id?: string
          user_id?: string
          position?: number
          set_type?: string
          weight_kg?: number | null
          reps?: number | null
          rpe?: number | null
          seconds?: number | null
          distance_m?: number | null
          completed?: boolean
          completed_at?: string | null
          notes?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_sets_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_sets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_sets_workout_exercise_id_fkey"
            columns: ["workout_exercise_id"]
            isOneToOne: false
            referencedRelation: "workout_exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_sets_workout_id_fkey"
            columns: ["workout_id"]
            isOneToOne: false
            referencedRelation: "workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      workouts: {
        Row: {
          id: string
          user_id: string
          routine_id: string | null
          name: string
          started_at: string
          finished_at: string | null
          notes: string | null
          bodyweight_kg: number | null
          activity_id: string | null
          linked_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          routine_id?: string | null
          name: string
          started_at?: string
          finished_at?: string | null
          notes?: string | null
          bodyweight_kg?: number | null
          activity_id?: string | null
          linked_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          routine_id?: string | null
          name?: string
          started_at?: string
          finished_at?: string | null
          notes?: string | null
          bodyweight_kg?: number | null
          activity_id?: string | null
          linked_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "workouts_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workouts_routine_id_fkey"
            columns: ["routine_id"]
            isOneToOne: false
            referencedRelation: "routines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workouts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      exercise_records: {
        Row: {
          user_id: string | null
          exercise_id: string | null
          best_weight_kg: number | null
          best_e1rm_kg: number | null
          best_set_volume_kg: number | null
          best_reps: number | null
          best_seconds: number | null
          completed_sets: number | null
          last_completed_at: string | null
        }
        Relationships: []
      }
      workout_summaries: {
        Row: {
          id: string | null
          user_id: string | null
          routine_id: string | null
          name: string | null
          started_at: string | null
          finished_at: string | null
          notes: string | null
          bodyweight_kg: number | null
          activity_id: string | null
          linked_by: string | null
          updated_at: string | null
          duration_s: number | null
          exercises: number | null
          sets_completed: number | null
          volume_kg: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      connect_intervals: {
        Args: {
          p_athlete_id: string
          p_api_key: string
          p_oldest?: string
        }
        Returns: undefined
      }
      delete_my_account: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
      disconnect_intervals: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"]
